#!/usr/bin/env bash

NOCOLOR="\033[0m"
BASH=$(command -v bash)
MUNT=$(command -v mount)
copy=$(command -v cp)
change_root=$(command -v chroot)
change_systemd_root=$(command -v systemd-nspawn)
change_prompt="export PS1=\"(chroot) $PS1\""
sys_init=$(strings /sbin/init | gawk 'match($0, /(upstart|systemd|sysvinit)/) { print toupper(substr($0, RSTART, RLENGTH));exit; }')

#One should have superuser privilege to work with this script.

if [[ $UID != "0" ]];then

  printf "You don't have enough privilege to utilise this tool.Use it with sudo or root :(  \n\n"
  exit 1
fi

#Usage help
usage() {

   printf "You forgot to mention either the target directory name or the partiton or both ...aborting. \

       Usage : change_os_root partition_number target_dir 
                              (sd[abc][123]) (/mnt or /whereever you like)

\n\n"
exit 1
}

blkid | gawk '{ print $1 $5 }' | grep -v /dev/mapper | grep PARTLABEL | sed 's/PARTLABEL=//'

printf "\n\n Which partition or OS root you want to access: %s"
read -r slice

printf "\n Well, you want to access $slice \n\n"

ls /

printf "\n Under which directory you want to mount the partition? : %s"

read -r chroot_dir

printf "\n You wanted to mount it on $chroot_dir \n"

if [  -z "$slice" ] || [ -z "$chroot_dir" ];then

    usage

#Checkin system INIT type and taking appropriate action to respective to that system.

elif [[ "$sys_init" == "SYSTEMD" ]];then

        printf "Chrooting to other OS ....  \n\n\n"

	printf "This is a SYSTEMD system, taking appropriate actions... \n\n"

	$MUNT /dev/$slice $chroot_dir
	$change_systemd_root -bD $chroot_dir

elif [[ "$sys_init" == "SYSVINIT" ]];then

     printf "Chrooting to other OS ....   \n\n\n"

     printf "This is a SYSVINIT system,taking appropriate actions... \n\n"


   printf "Doing other related stuff...wait \n\n"

     $MUNT /dev/$slice $chroot_dir
     $MUNT --rbind /dev $chroot_dir/dev
     $MUNT --make-rslave $chroot_dir/dev
     $MUNT -t proc /proc $chroot_dir/proc
     $MUNT --rbind /sys $chroot_dir/sys
     $MUNT --make-rslave $chroot_dir/sys
     $MUNT --rbind /tmp $chroot_dir/tmp
     $copy  /etc/resolv.conf $chroot_dir/etc/


printf "Getting into the chroot environment and change the prompt for recognization ,please run at shell. 

                           export PS1=\"(chroot) \$PS1\"

 \n\n"

  $change_root $chroot_dir $BASH

else
   printf "Error encounter...inspect manually."
          usage

fi


printf "Well, leaving the chroot shell and unmounting the slice from mounted dir ... \n\n"

trap EXIT

umount -l $chroot_dir


exit 0


