#!/bin/bash
#name=$1
#
#if [[ $name == "" ]];then
#	echo you are suppose to provide the video name.
#	exit 1
#fi

#ffmpeg -f x11grab  -r 25   -i :0  -vcodec libx264 -ac 2 -acodec libmp3lame screencast_$(date +'%F_%T').mkv
ffmpeg -f alsa -ac 2 -i pulse  -f x11grab  -r 25   -i :0  -vcodec libx264 -acodec pcm_s16le screencast_$(date +'%F_%T').mkv

